/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGJAVA
#define SWIGJAVA
#endif


/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include "parc_Identity.h"


void parcIdentity_Release1(PARCIdentity *identityPtr) {
     parcIdentity_Release(&identityPtr);
}


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void JNICALL Java_parc_security_ParcIdentity_PARCIdentityInterface_1Acquire_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct parc_identity_interface *arg1 = (struct parc_identity_interface *) 0 ;
  PARCIdentity *(*arg2)(void *) = (PARCIdentity *(*)(void *)) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct parc_identity_interface **)&jarg1; 
  arg2 = *(PARCIdentity *(**)(void *))&jarg2; 
  if (arg1) (arg1)->Acquire = arg2;
}


SWIGEXPORT jlong JNICALL Java_parc_security_ParcIdentity_PARCIdentityInterface_1Acquire_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct parc_identity_interface *arg1 = (struct parc_identity_interface *) 0 ;
  PARCIdentity *(*result)(void *) = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct parc_identity_interface **)&jarg1; 
  result = (PARCIdentity *(*)(void *)) ((arg1)->Acquire);
  *(PARCIdentity *(**)(void *))&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_parc_security_ParcIdentity_PARCIdentityInterface_1Release_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct parc_identity_interface *arg1 = (struct parc_identity_interface *) 0 ;
  void (*arg2)(void **) = (void (*)(void **)) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct parc_identity_interface **)&jarg1; 
  arg2 = *(void (**)(void **))&jarg2; 
  if (arg1) (arg1)->Release = arg2;
}


SWIGEXPORT jlong JNICALL Java_parc_security_ParcIdentity_PARCIdentityInterface_1Release_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct parc_identity_interface *arg1 = (struct parc_identity_interface *) 0 ;
  void (*result)(void **) = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct parc_identity_interface **)&jarg1; 
  result = (void (*)(void **)) ((arg1)->Release);
  *(void (**)(void **))&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_parc_security_ParcIdentity_PARCIdentityInterface_1GetPassWord_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct parc_identity_interface *arg1 = (struct parc_identity_interface *) 0 ;
  void *(*arg2)(void const *) = (void *(*)(void const *)) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct parc_identity_interface **)&jarg1; 
  arg2 = *(void *(**)(void const *))&jarg2; 
  if (arg1) (arg1)->GetPassWord = arg2;
}


SWIGEXPORT jlong JNICALL Java_parc_security_ParcIdentity_PARCIdentityInterface_1GetPassWord_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct parc_identity_interface *arg1 = (struct parc_identity_interface *) 0 ;
  void *(*result)(void const *) = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct parc_identity_interface **)&jarg1; 
  result = (void *(*)(void const *)) ((arg1)->GetPassWord);
  *(void *(**)(void const *))&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_parc_security_ParcIdentity_PARCIdentityInterface_1GetFileName_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct parc_identity_interface *arg1 = (struct parc_identity_interface *) 0 ;
  void *(*arg2)(void const *) = (void *(*)(void const *)) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct parc_identity_interface **)&jarg1; 
  arg2 = *(void *(**)(void const *))&jarg2; 
  if (arg1) (arg1)->GetFileName = arg2;
}


SWIGEXPORT jlong JNICALL Java_parc_security_ParcIdentity_PARCIdentityInterface_1GetFileName_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct parc_identity_interface *arg1 = (struct parc_identity_interface *) 0 ;
  void *(*result)(void const *) = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct parc_identity_interface **)&jarg1; 
  result = (void *(*)(void const *)) ((arg1)->GetFileName);
  *(void *(**)(void const *))&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_parc_security_ParcIdentity_PARCIdentityInterface_1GetSigner_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct parc_identity_interface *arg1 = (struct parc_identity_interface *) 0 ;
  PARCSigner *(*arg2)(void const *) = (PARCSigner *(*)(void const *)) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct parc_identity_interface **)&jarg1; 
  arg2 = *(PARCSigner *(**)(void const *))&jarg2; 
  if (arg1) (arg1)->GetSigner = arg2;
}


SWIGEXPORT jlong JNICALL Java_parc_security_ParcIdentity_PARCIdentityInterface_1GetSigner_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct parc_identity_interface *arg1 = (struct parc_identity_interface *) 0 ;
  PARCSigner *(*result)(void const *) = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct parc_identity_interface **)&jarg1; 
  result = (PARCSigner *(*)(void const *)) ((arg1)->GetSigner);
  *(PARCSigner *(**)(void const *))&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_parc_security_ParcIdentity_PARCIdentityInterface_1Equals_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct parc_identity_interface *arg1 = (struct parc_identity_interface *) 0 ;
  bool (*arg2)(void const *,void const *) = (bool (*)(void const *,void const *)) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct parc_identity_interface **)&jarg1; 
  arg2 = *(bool (**)(void const *,void const *))&jarg2; 
  if (arg1) (arg1)->Equals = arg2;
}


SWIGEXPORT jlong JNICALL Java_parc_security_ParcIdentity_PARCIdentityInterface_1Equals_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct parc_identity_interface *arg1 = (struct parc_identity_interface *) 0 ;
  bool (*result)(void const *,void const *) = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct parc_identity_interface **)&jarg1; 
  result = (bool (*)(void const *,void const *)) ((arg1)->Equals);
  *(bool (**)(void const *,void const *))&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_parc_security_ParcIdentity_PARCIdentityInterface_1Display_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct parc_identity_interface *arg1 = (struct parc_identity_interface *) 0 ;
  void (*arg2)(void const *,size_t) = (void (*)(void const *,size_t)) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct parc_identity_interface **)&jarg1; 
  arg2 = *(void (**)(void const *,size_t))&jarg2; 
  if (arg1) (arg1)->Display = arg2;
}


SWIGEXPORT jlong JNICALL Java_parc_security_ParcIdentity_PARCIdentityInterface_1Display_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct parc_identity_interface *arg1 = (struct parc_identity_interface *) 0 ;
  void (*result)(void const *,size_t) = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct parc_identity_interface **)&jarg1; 
  result = (void (*)(void const *,size_t)) ((arg1)->Display);
  *(void (**)(void const *,size_t))&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_parc_security_ParcIdentity_new_1PARCIdentityInterface(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct parc_identity_interface *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct parc_identity_interface *)calloc(1, sizeof(struct parc_identity_interface));
  *(struct parc_identity_interface **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_parc_security_ParcIdentity_delete_1PARCIdentityInterface(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct parc_identity_interface *arg1 = (struct parc_identity_interface *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct parc_identity_interface **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT jboolean JNICALL Java_parc_security_ParcIdentity_parcIdentity_1IsValid(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jboolean jresult = 0 ;
  PARCIdentity *arg1 = (PARCIdentity *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCIdentity **)&jarg1; 
  result = (bool)parcIdentity_IsValid((struct parc_identity const *)arg1);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_parc_security_ParcIdentity_parcIdentity_1AssertValid(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  PARCIdentity *arg1 = (PARCIdentity *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCIdentity **)&jarg1; 
  parcIdentity_AssertValid((struct parc_identity const *)arg1);
}


SWIGEXPORT jlong JNICALL Java_parc_security_ParcIdentity_parcIdentity_1Create(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jobject jarg2_) {
  jlong jresult = 0 ;
  PARCObject *arg1 = (PARCObject *) 0 ;
  PARCIdentityInterface *arg2 = (PARCIdentityInterface *) 0 ;
  PARCIdentity *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg2_;
  arg1 = *(PARCObject **)&jarg1; 
  arg2 = *(PARCIdentityInterface **)&jarg2; 
  result = (PARCIdentity *)parcIdentity_Create(arg1,(struct parc_identity_interface const *)arg2);
  *(PARCIdentity **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_parc_security_ParcIdentity_parcIdentity_1Acquire(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  PARCIdentity *arg1 = (PARCIdentity *) 0 ;
  PARCIdentity *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCIdentity **)&jarg1; 
  result = (PARCIdentity *)parcIdentity_Acquire((struct parc_identity const *)arg1);
  *(PARCIdentity **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_parc_security_ParcIdentity_parcIdentity_1Release(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  PARCIdentity **arg1 = (PARCIdentity **) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCIdentity ***)&jarg1; 
  parcIdentity_Release(arg1);
}


SWIGEXPORT jstring JNICALL Java_parc_security_ParcIdentity_parcIdentity_1GetFileName(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jstring jresult = 0 ;
  PARCIdentity *arg1 = (PARCIdentity *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCIdentity **)&jarg1; 
  result = (char *)parcIdentity_GetFileName((struct parc_identity const *)arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_parc_security_ParcIdentity_parcIdentity_1GetPassWord(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jstring jresult = 0 ;
  PARCIdentity *arg1 = (PARCIdentity *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCIdentity **)&jarg1; 
  result = (char *)parcIdentity_GetPassWord((struct parc_identity const *)arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_parc_security_ParcIdentity_parcIdentity_1CreateSigner(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  PARCIdentity *arg1 = (PARCIdentity *) 0 ;
  PARCSigner *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCIdentity **)&jarg1; 
  result = (PARCSigner *)parcIdentity_CreateSigner((struct parc_identity const *)arg1);
  *(PARCSigner **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_parc_security_ParcIdentity_parcIdentity_1Equals(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jboolean jresult = 0 ;
  PARCIdentity *arg1 = (PARCIdentity *) 0 ;
  PARCIdentity *arg2 = (PARCIdentity *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCIdentity **)&jarg1; 
  arg2 = *(PARCIdentity **)&jarg2; 
  result = (bool)parcIdentity_Equals((struct parc_identity const *)arg1,(struct parc_identity const *)arg2);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_parc_security_ParcIdentity_parcIdentity_1Display(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  PARCIdentity *arg1 = (PARCIdentity *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCIdentity **)&jarg1; 
  arg2 = (int)jarg2; 
  parcIdentity_Display((struct parc_identity const *)arg1,arg2);
}


SWIGEXPORT void JNICALL Java_parc_security_ParcIdentity_parcIdentity_1Release1(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  PARCIdentity *arg1 = (PARCIdentity *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCIdentity **)&jarg1; 
  parcIdentity_Release1(arg1);
}


#ifdef __cplusplus
}
#endif

