/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGJAVA
#define SWIGJAVA
#endif


/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include "parc_Buffer.h"


#include <stdint.h>		// Use the C99 official header


void parcBuffer_Release1(PARCBuffer *bufferPtr) {
    parcBuffer_Release(&bufferPtr);
}


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1AssertValid(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  PARCBuffer *arg1 = (PARCBuffer *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCBuffer **)&jarg1; 
  parcBuffer_AssertValid((struct parc_buffer const *)arg1);
}


SWIGEXPORT jboolean JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1IsValid(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jboolean jresult = 0 ;
  PARCBuffer *arg1 = (PARCBuffer *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCBuffer **)&jarg1; 
  result = (bool)parcBuffer_IsValid((struct parc_buffer const *)arg1);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1Allocate(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  size_t arg1 ;
  PARCBuffer *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (size_t)jarg1; 
  result = (PARCBuffer *)parcBuffer_Allocate(arg1);
  *(PARCBuffer **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1Wrap(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4) {
  jlong jresult = 0 ;
  void *arg1 = (void *) 0 ;
  size_t arg2 ;
  size_t arg3 ;
  size_t arg4 ;
  PARCBuffer *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(void **)&jarg1; 
  arg2 = (size_t)jarg2; 
  arg3 = (size_t)jarg3; 
  arg4 = (size_t)jarg4; 
  result = (PARCBuffer *)parcBuffer_Wrap(arg1,arg2,arg3,arg4);
  *(PARCBuffer **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1WrapByteArray(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  PARCByteArray *arg1 = (PARCByteArray *) 0 ;
  size_t arg2 ;
  size_t arg3 ;
  PARCBuffer *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCByteArray **)&jarg1; 
  arg2 = (size_t)jarg2; 
  arg3 = (size_t)jarg3; 
  result = (PARCBuffer *)parcBuffer_WrapByteArray(arg1,arg2,arg3);
  *(PARCBuffer **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1WrapCString(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  PARCBuffer *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  result = (PARCBuffer *)parcBuffer_WrapCString(arg1);
  *(PARCBuffer **)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1AllocateCString(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  PARCBuffer *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  result = (PARCBuffer *)parcBuffer_AllocateCString((char const *)arg1);
  *(PARCBuffer **)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1CreateFromArray(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  void *arg1 = (void *) 0 ;
  size_t arg2 ;
  PARCBuffer *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(void **)&jarg1; 
  arg2 = (size_t)jarg2; 
  result = (PARCBuffer *)parcBuffer_CreateFromArray((void const *)arg1,arg2);
  *(PARCBuffer **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1ParseHexString(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  PARCBuffer *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  result = (PARCBuffer *)parcBuffer_ParseHexString((char const *)arg1);
  *(PARCBuffer **)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1Resize(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  PARCBuffer *arg1 = (PARCBuffer *) 0 ;
  size_t arg2 ;
  PARCBuffer *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCBuffer **)&jarg1; 
  arg2 = (size_t)jarg2; 
  result = (PARCBuffer *)parcBuffer_Resize(arg1,arg2);
  *(PARCBuffer **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1Acquire(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  PARCBuffer *arg1 = (PARCBuffer *) 0 ;
  PARCBuffer *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCBuffer **)&jarg1; 
  result = (PARCBuffer *)parcBuffer_Acquire((struct parc_buffer const *)arg1);
  *(PARCBuffer **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1Release(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  PARCBuffer **arg1 = (PARCBuffer **) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCBuffer ***)&jarg1; 
  parcBuffer_Release(arg1);
}


SWIGEXPORT jlong JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1Capacity(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  PARCBuffer *arg1 = (PARCBuffer *) 0 ;
  size_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCBuffer **)&jarg1; 
  result = parcBuffer_Capacity((struct parc_buffer const *)arg1);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1Clear(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  PARCBuffer *arg1 = (PARCBuffer *) 0 ;
  PARCBuffer *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCBuffer **)&jarg1; 
  result = (PARCBuffer *)parcBuffer_Clear(arg1);
  *(PARCBuffer **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1Equals(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jboolean jresult = 0 ;
  PARCBuffer *arg1 = (PARCBuffer *) 0 ;
  PARCBuffer *arg2 = (PARCBuffer *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCBuffer **)&jarg1; 
  arg2 = *(PARCBuffer **)&jarg2; 
  result = (bool)parcBuffer_Equals((struct parc_buffer const *)arg1,(struct parc_buffer const *)arg2);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1Compare(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jint jresult = 0 ;
  PARCBuffer *arg1 = (PARCBuffer *) 0 ;
  PARCBuffer *arg2 = (PARCBuffer *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCBuffer **)&jarg1; 
  arg2 = *(PARCBuffer **)&jarg2; 
  result = (int)parcBuffer_Compare((struct parc_buffer const *)arg1,(struct parc_buffer const *)arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1Array(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  PARCBuffer *arg1 = (PARCBuffer *) 0 ;
  PARCByteArray *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCBuffer **)&jarg1; 
  result = (PARCByteArray *)parcBuffer_Array((struct parc_buffer const *)arg1);
  *(PARCByteArray **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1Copy(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  PARCBuffer *arg1 = (PARCBuffer *) 0 ;
  PARCBuffer *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCBuffer **)&jarg1; 
  result = (PARCBuffer *)parcBuffer_Copy((struct parc_buffer const *)arg1);
  *(PARCBuffer **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1Duplicate(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  PARCBuffer *arg1 = (PARCBuffer *) 0 ;
  PARCBuffer *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCBuffer **)&jarg1; 
  result = (PARCBuffer *)parcBuffer_Duplicate((struct parc_buffer const *)arg1);
  *(PARCBuffer **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1ArrayOffset(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  PARCBuffer *arg1 = (PARCBuffer *) 0 ;
  size_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCBuffer **)&jarg1; 
  result = parcBuffer_ArrayOffset((struct parc_buffer const *)arg1);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1Rewind(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  PARCBuffer *arg1 = (PARCBuffer *) 0 ;
  PARCBuffer *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCBuffer **)&jarg1; 
  result = (PARCBuffer *)parcBuffer_Rewind(arg1);
  *(PARCBuffer **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1Reset(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  PARCBuffer *arg1 = (PARCBuffer *) 0 ;
  PARCBuffer *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCBuffer **)&jarg1; 
  result = (PARCBuffer *)parcBuffer_Reset(arg1);
  *(PARCBuffer **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1Limit(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  PARCBuffer *arg1 = (PARCBuffer *) 0 ;
  size_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCBuffer **)&jarg1; 
  result = parcBuffer_Limit((struct parc_buffer const *)arg1);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1Mark(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  PARCBuffer *arg1 = (PARCBuffer *) 0 ;
  PARCBuffer *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCBuffer **)&jarg1; 
  result = (PARCBuffer *)parcBuffer_Mark(arg1);
  *(PARCBuffer **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1SetLimit(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  PARCBuffer *arg1 = (PARCBuffer *) 0 ;
  size_t arg2 ;
  PARCBuffer *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCBuffer **)&jarg1; 
  arg2 = (size_t)jarg2; 
  result = (PARCBuffer *)parcBuffer_SetLimit(arg1,arg2);
  *(PARCBuffer **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1Overlay(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  PARCBuffer *arg1 = (PARCBuffer *) 0 ;
  size_t arg2 ;
  void *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCBuffer **)&jarg1; 
  arg2 = (size_t)jarg2; 
  result = (void *)parcBuffer_Overlay(arg1,arg2);
  *(void **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1Position(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  PARCBuffer *arg1 = (PARCBuffer *) 0 ;
  size_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCBuffer **)&jarg1; 
  result = parcBuffer_Position((struct parc_buffer const *)arg1);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1SetPosition(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  PARCBuffer *arg1 = (PARCBuffer *) 0 ;
  size_t arg2 ;
  PARCBuffer *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCBuffer **)&jarg1; 
  arg2 = (size_t)jarg2; 
  result = (PARCBuffer *)parcBuffer_SetPosition(arg1,arg2);
  *(PARCBuffer **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1Remaining(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  PARCBuffer *arg1 = (PARCBuffer *) 0 ;
  size_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCBuffer **)&jarg1; 
  result = parcBuffer_Remaining((struct parc_buffer const *)arg1);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1HasRemaining(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jboolean jresult = 0 ;
  PARCBuffer *arg1 = (PARCBuffer *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCBuffer **)&jarg1; 
  result = (bool)parcBuffer_HasRemaining((struct parc_buffer const *)arg1);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1Slice(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  PARCBuffer *arg1 = (PARCBuffer *) 0 ;
  PARCBuffer *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCBuffer **)&jarg1; 
  result = (PARCBuffer *)parcBuffer_Slice((struct parc_buffer const *)arg1);
  *(PARCBuffer **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1Flip(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  PARCBuffer *arg1 = (PARCBuffer *) 0 ;
  PARCBuffer *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCBuffer **)&jarg1; 
  result = (PARCBuffer *)parcBuffer_Flip(arg1);
  *(PARCBuffer **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1GetAtIndex(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jshort jresult = 0 ;
  PARCBuffer *arg1 = (PARCBuffer *) 0 ;
  size_t arg2 ;
  uint8_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCBuffer **)&jarg1; 
  arg2 = (size_t)jarg2; 
  result = (uint8_t)parcBuffer_GetAtIndex((struct parc_buffer const *)arg1,arg2);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1GetUint8(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jshort jresult = 0 ;
  PARCBuffer *arg1 = (PARCBuffer *) 0 ;
  uint8_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCBuffer **)&jarg1; 
  result = (uint8_t)parcBuffer_GetUint8(arg1);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1GetUint16(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  PARCBuffer *arg1 = (PARCBuffer *) 0 ;
  uint16_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCBuffer **)&jarg1; 
  result = (uint16_t)parcBuffer_GetUint16(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1GetUint32(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  PARCBuffer *arg1 = (PARCBuffer *) 0 ;
  uint32_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCBuffer **)&jarg1; 
  result = (uint32_t)parcBuffer_GetUint32(arg1);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jobject JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1GetUint64(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jobject jresult = 0 ;
  PARCBuffer *arg1 = (PARCBuffer *) 0 ;
  uint64_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCBuffer **)&jarg1; 
  result = (uint64_t)parcBuffer_GetUint64(arg1);
  {
    jbyteArray ba = (*jenv)->NewByteArray(jenv, 9);
    jbyte* bae = (*jenv)->GetByteArrayElements(jenv, ba, 0);
    jclass clazz = (*jenv)->FindClass(jenv, "java/math/BigInteger");
    jmethodID mid = (*jenv)->GetMethodID(jenv, clazz, "<init>", "([B)V");
    jobject bigint;
    int i;
    
    bae[0] = 0;
    for(i=1; i<9; i++ ) {
      bae[i] = (jbyte)(result>>8*(8-i));
    }
    
    (*jenv)->ReleaseByteArrayElements(jenv, ba, bae, 0);
    bigint = (*jenv)->NewObject(jenv, clazz, mid, ba);
    jresult = bigint;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1GetBytes(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  PARCBuffer *arg1 = (PARCBuffer *) 0 ;
  size_t arg2 ;
  uint8_t *arg3 ;
  PARCBuffer *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCBuffer **)&jarg1; 
  arg2 = (size_t)jarg2; 
  arg3 = *(uint8_t **)&jarg3; 
  result = (PARCBuffer *)parcBuffer_GetBytes(arg1,arg2,arg3);
  *(PARCBuffer **)&jresult = result; 
  
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1PutUint8(JNIEnv *jenv, jclass jcls, jlong jarg1, jshort jarg2) {
  jlong jresult = 0 ;
  PARCBuffer *arg1 = (PARCBuffer *) 0 ;
  uint8_t arg2 ;
  PARCBuffer *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCBuffer **)&jarg1; 
  arg2 = (uint8_t)jarg2; 
  result = (PARCBuffer *)parcBuffer_PutUint8(arg1,arg2);
  *(PARCBuffer **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1PutUint16(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  jlong jresult = 0 ;
  PARCBuffer *arg1 = (PARCBuffer *) 0 ;
  uint16_t arg2 ;
  PARCBuffer *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCBuffer **)&jarg1; 
  arg2 = (uint16_t)jarg2; 
  result = (PARCBuffer *)parcBuffer_PutUint16(arg1,arg2);
  *(PARCBuffer **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1PutUint32(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  PARCBuffer *arg1 = (PARCBuffer *) 0 ;
  uint32_t arg2 ;
  PARCBuffer *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCBuffer **)&jarg1; 
  arg2 = (uint32_t)jarg2; 
  result = (PARCBuffer *)parcBuffer_PutUint32(arg1,arg2);
  *(PARCBuffer **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1PutUint64(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg2) {
  jlong jresult = 0 ;
  PARCBuffer *arg1 = (PARCBuffer *) 0 ;
  uint64_t arg2 ;
  PARCBuffer *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCBuffer **)&jarg1; 
  {
    jclass clazz;
    jmethodID mid;
    jbyteArray ba;
    jbyte* bae;
    jsize sz;
    int i;
    
    if (!jarg2) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "BigInteger null");
      return 0;
    }
    clazz = (*jenv)->GetObjectClass(jenv, jarg2);
    mid = (*jenv)->GetMethodID(jenv, clazz, "toByteArray", "()[B");
    ba = (jbyteArray)(*jenv)->CallObjectMethod(jenv, jarg2, mid);
    bae = (*jenv)->GetByteArrayElements(jenv, ba, 0);
    sz = (*jenv)->GetArrayLength(jenv, ba);
    arg2 = 0;
    for(i=0; i<sz; i++) {
      arg2 = (arg2 << 8) | (uint64_t)(unsigned char)bae[i];
    }
    (*jenv)->ReleaseByteArrayElements(jenv, ba, bae, 0);
  }
  result = (PARCBuffer *)parcBuffer_PutUint64(arg1,arg2);
  *(PARCBuffer **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1PutAtIndex(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jshort jarg3) {
  jlong jresult = 0 ;
  PARCBuffer *arg1 = (PARCBuffer *) 0 ;
  size_t arg2 ;
  uint8_t arg3 ;
  PARCBuffer *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCBuffer **)&jarg1; 
  arg2 = (size_t)jarg2; 
  arg3 = (uint8_t)jarg3; 
  result = (PARCBuffer *)parcBuffer_PutAtIndex(arg1,arg2,arg3);
  *(PARCBuffer **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1PutArray(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  PARCBuffer *arg1 = (PARCBuffer *) 0 ;
  size_t arg2 ;
  uint8_t *arg3 ;
  PARCBuffer *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCBuffer **)&jarg1; 
  arg2 = (size_t)jarg2; 
  arg3 = *(uint8_t **)&jarg3; 
  result = (PARCBuffer *)parcBuffer_PutArray(arg1,arg2,(unsigned char const (*))arg3);
  *(PARCBuffer **)&jresult = result; 
  
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1PutCString(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  jlong jresult = 0 ;
  PARCBuffer *arg1 = (PARCBuffer *) 0 ;
  char *arg2 = (char *) 0 ;
  PARCBuffer *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCBuffer **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (PARCBuffer *)parcBuffer_PutCString(arg1,(char const *)arg2);
  *(PARCBuffer **)&jresult = result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1PutBuffer(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  PARCBuffer *arg1 = (PARCBuffer *) 0 ;
  PARCBuffer *arg2 = (PARCBuffer *) 0 ;
  PARCBuffer *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCBuffer **)&jarg1; 
  arg2 = *(PARCBuffer **)&jarg2; 
  result = (PARCBuffer *)parcBuffer_PutBuffer(arg1,(struct parc_buffer const *)arg2);
  *(PARCBuffer **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1HashCode(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  PARCBuffer *arg1 = (PARCBuffer *) 0 ;
  PARCHashCode result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCBuffer **)&jarg1; 
  result = parcBuffer_HashCode((struct parc_buffer const *)arg1);
  {
    PARCHashCode * resultptr = (PARCHashCode *) malloc(sizeof(PARCHashCode));
    memmove(resultptr, &result, sizeof(PARCHashCode));
    *(PARCHashCode **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1FindUint8(JNIEnv *jenv, jclass jcls, jlong jarg1, jshort jarg2) {
  jlong jresult = 0 ;
  PARCBuffer *arg1 = (PARCBuffer *) 0 ;
  uint8_t arg2 ;
  size_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCBuffer **)&jarg1; 
  arg2 = (uint8_t)jarg2; 
  result = parcBuffer_FindUint8((struct parc_buffer const *)arg1,arg2);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1ToString(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jstring jresult = 0 ;
  PARCBuffer *arg1 = (PARCBuffer *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCBuffer **)&jarg1; 
  result = (char *)parcBuffer_ToString((struct parc_buffer const *)arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1Display(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  PARCBuffer *arg1 = (PARCBuffer *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCBuffer **)&jarg1; 
  arg2 = (int)jarg2; 
  parcBuffer_Display((struct parc_buffer const *)arg1,arg2);
}


SWIGEXPORT jstring JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1ToHexString(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jstring jresult = 0 ;
  PARCBuffer *arg1 = (PARCBuffer *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCBuffer **)&jarg1; 
  result = (char *)parcBuffer_ToHexString((struct parc_buffer const *)arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1SkipOver(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jboolean jresult = 0 ;
  PARCBuffer *arg1 = (PARCBuffer *) 0 ;
  size_t arg2 ;
  uint8_t *arg3 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCBuffer **)&jarg1; 
  arg2 = (size_t)jarg2; 
  arg3 = *(uint8_t **)&jarg3; 
  result = (bool)parcBuffer_SkipOver(arg1,arg2,(unsigned char const (*))arg3);
  jresult = (jboolean)result; 
  
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1SkipTo(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jboolean jresult = 0 ;
  PARCBuffer *arg1 = (PARCBuffer *) 0 ;
  size_t arg2 ;
  uint8_t *arg3 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCBuffer **)&jarg1; 
  arg2 = (size_t)jarg2; 
  arg3 = *(uint8_t **)&jarg3; 
  result = (bool)parcBuffer_SkipTo(arg1,arg2,(unsigned char const (*))arg3);
  jresult = (jboolean)result; 
  
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1PeekByte(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jshort jresult = 0 ;
  PARCBuffer *arg1 = (PARCBuffer *) 0 ;
  uint8_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCBuffer **)&jarg1; 
  result = (uint8_t)parcBuffer_PeekByte((struct parc_buffer const *)arg1);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jobject JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1ParseHexNumber(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jobject jresult = 0 ;
  PARCBuffer *arg1 = (PARCBuffer *) 0 ;
  uint64_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCBuffer **)&jarg1; 
  result = (uint64_t)parcBuffer_ParseHexNumber(arg1);
  {
    jbyteArray ba = (*jenv)->NewByteArray(jenv, 9);
    jbyte* bae = (*jenv)->GetByteArrayElements(jenv, ba, 0);
    jclass clazz = (*jenv)->FindClass(jenv, "java/math/BigInteger");
    jmethodID mid = (*jenv)->GetMethodID(jenv, clazz, "<init>", "([B)V");
    jobject bigint;
    int i;
    
    bae[0] = 0;
    for(i=1; i<9; i++ ) {
      bae[i] = (jbyte)(result>>8*(8-i));
    }
    
    (*jenv)->ReleaseByteArrayElements(jenv, ba, bae, 0);
    bigint = (*jenv)->NewObject(jenv, clazz, mid, ba);
    jresult = bigint;
  }
  return jresult;
}


SWIGEXPORT jobject JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1ParseDecimalNumber(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jobject jresult = 0 ;
  PARCBuffer *arg1 = (PARCBuffer *) 0 ;
  uint64_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCBuffer **)&jarg1; 
  result = (uint64_t)parcBuffer_ParseDecimalNumber(arg1);
  {
    jbyteArray ba = (*jenv)->NewByteArray(jenv, 9);
    jbyte* bae = (*jenv)->GetByteArrayElements(jenv, ba, 0);
    jclass clazz = (*jenv)->FindClass(jenv, "java/math/BigInteger");
    jmethodID mid = (*jenv)->GetMethodID(jenv, clazz, "<init>", "([B)V");
    jobject bigint;
    int i;
    
    bae[0] = 0;
    for(i=1; i<9; i++ ) {
      bae[i] = (jbyte)(result>>8*(8-i));
    }
    
    (*jenv)->ReleaseByteArrayElements(jenv, ba, bae, 0);
    bigint = (*jenv)->NewObject(jenv, clazz, mid, ba);
    jresult = bigint;
  }
  return jresult;
}


SWIGEXPORT jobject JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1ParseNumeric(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jobject jresult = 0 ;
  PARCBuffer *arg1 = (PARCBuffer *) 0 ;
  uint64_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCBuffer **)&jarg1; 
  result = (uint64_t)parcBuffer_ParseNumeric(arg1);
  {
    jbyteArray ba = (*jenv)->NewByteArray(jenv, 9);
    jbyte* bae = (*jenv)->GetByteArrayElements(jenv, ba, 0);
    jclass clazz = (*jenv)->FindClass(jenv, "java/math/BigInteger");
    jmethodID mid = (*jenv)->GetMethodID(jenv, clazz, "<init>", "([B)V");
    jobject bigint;
    int i;
    
    bae[0] = 0;
    for(i=1; i<9; i++ ) {
      bae[i] = (jbyte)(result>>8*(8-i));
    }
    
    (*jenv)->ReleaseByteArrayElements(jenv, ba, bae, 0);
    bigint = (*jenv)->NewObject(jenv, clazz, mid, ba);
    jresult = bigint;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_parc_algol_ParcBuffer_parcBuffer_1Release1(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  PARCBuffer *arg1 = (PARCBuffer *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCBuffer **)&jarg1; 
  parcBuffer_Release1(arg1);
}


#ifdef __cplusplus
}
#endif

